### ISSUE TITLE
Issue with special characters (, ), \, 

### ISSUE THREAD

**Issue by chdagenais** [pocesar/js-diacritic-regex#4]
calling toRegex with a string containing open parenthesis `(`, `)` or backslash `\`,  return 
Uncaught SyntaxError: Invalid regular expression: /\/: \ at end of pattern

For example, calling `toRegex({ flags: 'i' })("résumé (");` throw

> Uncaught SyntaxError: Invalid regular expression: /r[EeÈèÉéÊêËë]s[UuÙùÚúÛûÜü]m[EeÈèÉéÊêËë] (/: Unterminated group

**Comment by pocesar** [comment]
yes, the input string must be sanitized, using something like https://github.com/sindresorhus/escape-string-regexp should suffice

**Comment by fawazahmed0** [comment]
@pocesar, Hi, just thought of sharing it with you,
I ended up using something like this:
`"résumé".normalize('NFD').replace(/[\u0300-\u036f]/g, '')`
It will remove all the diacritical marks
Reference: https://thread.engineering/2018-08-29-searching-and-sorting-text-with-diacritical-marks-in-javascript/
